$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
properties:
  messages:
    type: object
    additionalProperties:
      type: object
      properties:
        message:
          type: string
        enabled:
          type: boolean
        recipients:
          type: array
          items:
            type: string
            oneOf:
              - pattern: "@.+\\..+"
              - enum: ["all", "logged_in", "guests"]
        trigger:
          type: object
          properties:
            event:
              type: string
              enum: ["on_chat_start", "on_chat_end", "on_chat_resume", "on_message"]
            after_messages:
              type: integer
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
            freq_max:
              type: string
              pattern: "^[0-9]+[smhdw]$"
          anyOf:
            - required: ["event"]
            - required: ["after_messages"]
      required: ["message", "trigger"]
required: ["messages"]
