version: '3.8'

services:
  chainlit:
    image: reactome-chatbot
    container_name: biochat_chainlit
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - LOG_LEVEL=${LOG_LEVEL}
      - CHAT_ENV=${CHAT_ENV}
      - CLOUDFLARE_SECRET_KEY=${CLOUDFLARE_SECRET_KEY}
      - CLOUDFLARE_SITE_KEY=${CLOUDFLARE_SITE_KEY}
      - OAUTH_AUTH0_CLIENT_ID=${OAUTH_AUTH0_CLIENT_ID}
      - OAUTH_AUTH0_CLIENT_SECRET=${OAUTH_AUTH0_CLIENT_SECRET}
      - OAUTH_AUTH0_DOMAIN=${OAUTH_AUTH0_DOMAIN}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./embeddings:/app/embeddings

  postgres:
    image: postgres:13
    container_name: biochat_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: 'test@test.com'
        PGADMIN_DEFAULT_PASSWORD: 'test'
      ports:
        - 16543:80
      volumes:
        - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
