[tool.poetry]
name = "reactome-chatbot"
version = "0.1.0"
description = "Chatbot for reactome's data portal"
authors = ["Helia Mohammadi <hmohammadi@oicr.on.ca>"]
license = "Apache2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.1.9"
openai = "^1.12.0"
chromadb = "^0.4.24"
pandas = "^2.2.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.2"
pytest = "^8.0.2"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
