biocypher:
  #— Which backend to target (CSV for Neo4j admin import)
  dbms: neo4j                           # 
  offline: true                         # dump CSVs, don't push live
  strict_mode: false
  debug: true
  batch_size: 100000                    # Consolidate CSV files

  #— Schema and ontology
  schema_config_path: config/schema_config.yaml
  head_ontology:
    url:   https://github.com/biolink/biolink-model/raw/v3.2.1/biolink-model.owl.ttl
    root_node: entity
    switch_label_and_id: true

  #— Logging & I/O
  log_to_disk:     true
  log_directory:   biocypher-log
  output_directory: biocypher-out/enhanced_reactome_kg      # where CSVs will land 
  cache_directory: .cache

  output_path:     biocypher-out/enhanced_reactome_kg 

#————————————————————————————————
# Neo4j-specific settings
#————————————————————————————————
neo4j:
  database_name:   neo4j
  multi_db:        false
  wipe:            true               # start fresh each run

  uri:             bolt://localhost:7687  # match your Docker port
  user:            neo4j
  password:        reactome

  #— CSV import parameters for neo4j-admin
  delimiter:       ";"                # field delimiter
  array_delimiter: "|"                # for lists
  quote_character: "@"                # quoting strings

  #— Multi‑DB support (Neo4j 4+)
  skip_duplicate_nodes:    false
  skip_bad_relationships: true
