name: 'Setup Python and Poetry'
description: 'Setup Python environment and install Poetry'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
